=== ManhKieuDuy/TichHop-HeThong/DeCongTy2_TichHop/src/main/java/DeCongTy2_TichHop/congty.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
	
    <xs:simpleType name="scoreCondition">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="10"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="classification">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Average"/>
            <xs:enumeration value="Good"/>
            <xs:enumeration value="Excellent"/>
            <xs:enumeration value="Weak"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="teacher">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Tran Mai Linh"/>
            <xs:enumeration value="Dang Thi Nhung"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="academicresults">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="academicyear" type="xs:string"/>
                <xs:element name="studentresult" minOccurs="3" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="stdid">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{8}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="fullname" type="xs:string"/>
                            <xs:element name="dateofbirth" type="xs:date"/>
                            <xs:element name="class" type="xs:string"/>
                            <xs:element name="subjectresult" minOccurs="3" maxOccurs="5">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="subject"/>
                                        <xs:element name="attempt1" type="scoreCondition"/>
                                        <xs:element name="attempt2" type="scoreCondition"/>
                                        <xs:element name="annualscore" type="scoreCondition"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="academicclassification" type="classification"></xs:element>
                            <xs:element name="conductclassification" type="classification"></xs:element>
                            <xs:element name="homeroomteacher" type="teacher"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
		
    </xs:element>
</xs:schema>

=== ManhKieuDuy/TichHop-HeThong/DeCongTy2_TichHop/src/main/java/DeCongTy2_TichHop/congty.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl href="congty.xsl"?>
<academicresults
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='congty.xsd'>
    <academicyear>2009</academicyear>
    <studentresult>
        <stdid>01234567</stdid>
        <fullname>Kieu Duy Manh</fullname>
        <dateofbirth>2000-04-01</dateofbirth>
        <class>CNTT01TA</class>
        <subjectresult>
            <subject>Software System Intergration</subject>
            <attempt1>9</attempt1>
            <attempt2>9</attempt2>
            <annualscore>10</annualscore>
        </subjectresult>
        <subjectresult>
            <subject>Major Project</subject>
            <attempt1>9</attempt1>
            <attempt2>9</attempt2>
            <annualscore>9</annualscore>
        </subjectresult>
        <subjectresult>
            <subject>Software Testing</subject>
            <attempt1>9</attempt1>
            <attempt2>9</attempt2>
            <annualscore>9</annualscore>
        </subjectresult>
        <academicclassification>Good</academicclassification>
        <conductclassification>Good</conductclassification>
        <homeroomteacher>Tran Mai Linh</homeroomteacher>
    </studentresult>
    <studentresult>
        <stdid>02234567</stdid>
        <fullname>Nguyen Van Nam</fullname>
        <dateofbirth>2001-12-07</dateofbirth>
        <class>CNTT01TA</class>
        <subjectresult>
            <subject>Software System Intergration</subject>
            <attempt1>9</attempt1>
            <attempt2>9</attempt2>
            <annualscore>10</annualscore>
        </subjectresult>
        <subjectresult>
            <subject>Major Project</subject>
            <attempt1>9</attempt1>
            <attempt2>9</attempt2>
            <annualscore>9</annualscore>
        </subjectresult>
        <subjectresult>
            <subject>Software Testing</subject>
            <attempt1>9</attempt1>
            <attempt2>9</attempt2>
            <annualscore>9</annualscore>
        </subjectresult>
        <academicclassification>Weak</academicclassification>
        <conductclassification>Good</conductclassification>
        <homeroomteacher>Dang Thi Nhung</homeroomteacher>
    </studentresult>
    <studentresult>
        <stdid>03234567</stdid>
        <fullname>Kieu Thi Nu</fullname>
        <dateofbirth>2000-08-23</dateofbirth>
        <class></class>
        <subjectresult>
            <subject>Software System Intergration</subject>
            <attempt1>7</attempt1>
            <attempt2>8</attempt2>
            <annualscore>7</annualscore>
        </subjectresult>
        <subjectresult>
            <subject>Major Project</subject>
            <attempt1>5</attempt1>
            <attempt2>7</attempt2>
            <annualscore>8</annualscore>
        </subjectresult>
        <subjectresult>
            <subject>Software Testing</subject>
            <attempt1>6</attempt1>
            <attempt2>7</attempt2>
            <annualscore>7</annualscore>
        </subjectresult>
        <academicclassification>Excellent</academicclassification>
        <conductclassification>Good</conductclassification>
        <homeroomteacher>Dang Thi Nhung</homeroomteacher>
    </studentresult>

</academicresults>
