=== ManhKieuDuy/TichHop-HeThong/De1_TichHop/src/main/java/De1/congty.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="congty">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="phongban" minOccurs="2" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tenphong">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Tổ chức"/>
                                        <xs:enumeration value="Hành chính"/>
                                        <xs:enumeration value="Đào tạo"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="dienthoai">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="0[0-9]{9}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="nhanvien" minOccurs="3" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="manv" type="xs:string"></xs:element>
                                        <xs:element name="hoten">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="trinhdo" type="xs:string"></xs:element>
                                        <xs:element name="mucluong" type="xs:int"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="maphong" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ManhKieuDuy/TichHop-HeThong/De1_TichHop/src/main/java/De1/congty.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="congty.xsl"?>
<congty
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='congty.xsd'>
    <phongban maphong="p01">
        <tenphong>Tổ chức</tenphong>
        <dienthoai>0123456789</dienthoai>
        <nhanvien>
            <manv>nv01</manv>
            <hoten>Phan Tuyết Nga</hoten>
            <trinhdo>Đại học</trinhdo>
            <mucluong>1888</mucluong>
        </nhanvien>
        <nhanvien>
            <manv>nv02</manv>
            <hoten>Hoàng Văn Long</hoten>
            <trinhdo>Đại học</trinhdo>
            <mucluong>273</mucluong>
        </nhanvien>
        <nhanvien>
            <manv>nv03</manv>
            <hoten>Kiều Duy Mạnh</hoten>
            <trinhdo>Đại học</trinhdo>
            <mucluong>3647</mucluong>
        </nhanvien>
    </phongban>
    <phongban maphong="p02">
        <tenphong>Hành chính</tenphong>
        <dienthoai>0123456789</dienthoai>
        <nhanvien>
            <manv>nv04</manv>
            <hoten>Phan Văn Anh</hoten>
            <trinhdo>Đại học</trinhdo>
            <mucluong>736</mucluong>
        </nhanvien>
        <nhanvien>
            <manv>nv05</manv>
            <hoten>Đỗ Nam Trung</hoten>
            <trinhdo>Đại học</trinhdo>
            <mucluong>9822</mucluong>
        </nhanvien>
        <nhanvien>
            <manv>nv06</manv>
            <hoten>Nguyễn Văn Ba</hoten>
            <trinhdo>Đại học</trinhdo>
            <mucluong>764</mucluong>
        </nhanvien>
    </phongban>

</congty>
